#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mimi2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mini")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Artist(tbl_Artist instance);
    partial void Updatetbl_Artist(tbl_Artist instance);
    partial void Deletetbl_Artist(tbl_Artist instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["miniConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fb> fbs
		{
			get
			{
				return this.GetTable<fb>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Artist> tbl_Artists
		{
			get
			{
				return this.GetTable<tbl_Artist>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.take1")]
		public ISingleResult<take1Result> take1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<take1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.upda")]
		public int upda([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, email, phone, gender, dob, pass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.log1")]
		public ISingleResult<log1Result> log1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string useid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string pass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), useid, pass);
			return ((ISingleResult<log1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.check1")]
		public ISingleResult<check1Result> check1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<check1Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.change")]
		public int change([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string newpass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, newpass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.forget")]
		public ISingleResult<forgetResult> forget([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<forgetResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.emailcheck")]
		public ISingleResult<emailcheckResult> emailcheck([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<emailcheckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mobcheck")]
		public ISingleResult<mobcheckResult> mobcheck([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string mob)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mob);
			return ((ISingleResult<mobcheckResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pickcat")]
		public ISingleResult<pickcatResult> pickcat()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<pickcatResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fb")]
	public partial class fb
	{
		
		private int _f_id;
		
		private string _f_name;
		
		private string _f_email;
		
		private System.Nullable<int> _f_phone;
		
		public fb()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int f_id
		{
			get
			{
				return this._f_id;
			}
			set
			{
				if ((this._f_id != value))
				{
					this._f_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_name", DbType="VarChar(50)")]
		public string f_name
		{
			get
			{
				return this._f_name;
			}
			set
			{
				if ((this._f_name != value))
				{
					this._f_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_email", DbType="VarChar(50)")]
		public string f_email
		{
			get
			{
				return this._f_email;
			}
			set
			{
				if ((this._f_email != value))
				{
					this._f_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_phone", DbType="Int")]
		public System.Nullable<int> f_phone
		{
			get
			{
				return this._f_phone;
			}
			set
			{
				if ((this._f_phone != value))
				{
					this._f_phone = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Artist")]
	public partial class tbl_Artist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Art_ID;
		
		private string _Art_Name;
		
		private string _Art_Email;
		
		private System.Nullable<int> _Art_phone;
		
		private string _Art_Gender;
		
		private System.Nullable<System.DateTime> _Art_Dob;
		
		private string _Art_Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArt_IDChanging(int value);
    partial void OnArt_IDChanged();
    partial void OnArt_NameChanging(string value);
    partial void OnArt_NameChanged();
    partial void OnArt_EmailChanging(string value);
    partial void OnArt_EmailChanged();
    partial void OnArt_phoneChanging(System.Nullable<int> value);
    partial void OnArt_phoneChanged();
    partial void OnArt_GenderChanging(string value);
    partial void OnArt_GenderChanged();
    partial void OnArt_DobChanging(System.Nullable<System.DateTime> value);
    partial void OnArt_DobChanged();
    partial void OnArt_PasswordChanging(string value);
    partial void OnArt_PasswordChanged();
    #endregion
		
		public tbl_Artist()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Art_ID
		{
			get
			{
				return this._Art_ID;
			}
			set
			{
				if ((this._Art_ID != value))
				{
					this.OnArt_IDChanging(value);
					this.SendPropertyChanging();
					this._Art_ID = value;
					this.SendPropertyChanged("Art_ID");
					this.OnArt_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Art_Name
		{
			get
			{
				return this._Art_Name;
			}
			set
			{
				if ((this._Art_Name != value))
				{
					this.OnArt_NameChanging(value);
					this.SendPropertyChanging();
					this._Art_Name = value;
					this.SendPropertyChanged("Art_Name");
					this.OnArt_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Email", DbType="VarChar(50)")]
		public string Art_Email
		{
			get
			{
				return this._Art_Email;
			}
			set
			{
				if ((this._Art_Email != value))
				{
					this.OnArt_EmailChanging(value);
					this.SendPropertyChanging();
					this._Art_Email = value;
					this.SendPropertyChanged("Art_Email");
					this.OnArt_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_phone", DbType="Int")]
		public System.Nullable<int> Art_phone
		{
			get
			{
				return this._Art_phone;
			}
			set
			{
				if ((this._Art_phone != value))
				{
					this.OnArt_phoneChanging(value);
					this.SendPropertyChanging();
					this._Art_phone = value;
					this.SendPropertyChanged("Art_phone");
					this.OnArt_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Gender", DbType="VarChar(6)")]
		public string Art_Gender
		{
			get
			{
				return this._Art_Gender;
			}
			set
			{
				if ((this._Art_Gender != value))
				{
					this.OnArt_GenderChanging(value);
					this.SendPropertyChanging();
					this._Art_Gender = value;
					this.SendPropertyChanged("Art_Gender");
					this.OnArt_GenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Dob", DbType="Date")]
		public System.Nullable<System.DateTime> Art_Dob
		{
			get
			{
				return this._Art_Dob;
			}
			set
			{
				if ((this._Art_Dob != value))
				{
					this.OnArt_DobChanging(value);
					this.SendPropertyChanging();
					this._Art_Dob = value;
					this.SendPropertyChanged("Art_Dob");
					this.OnArt_DobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Art_Password
		{
			get
			{
				return this._Art_Password;
			}
			set
			{
				if ((this._Art_Password != value))
				{
					this.OnArt_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Art_Password = value;
					this.SendPropertyChanged("Art_Password");
					this.OnArt_PasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class take1Result
	{
		
		private string _f_name;
		
		private string _f_email;
		
		private System.Nullable<int> _f_phone;
		
		public take1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_name", DbType="VarChar(50)")]
		public string f_name
		{
			get
			{
				return this._f_name;
			}
			set
			{
				if ((this._f_name != value))
				{
					this._f_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_email", DbType="VarChar(50)")]
		public string f_email
		{
			get
			{
				return this._f_email;
			}
			set
			{
				if ((this._f_email != value))
				{
					this._f_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_phone", DbType="Int")]
		public System.Nullable<int> f_phone
		{
			get
			{
				return this._f_phone;
			}
			set
			{
				if ((this._f_phone != value))
				{
					this._f_phone = value;
				}
			}
		}
	}
	
	public partial class log1Result
	{
		
		private int _Art_ID;
		
		private string _Art_Name;
		
		private string _Art_Email;
		
		private string _Art_phone;
		
		private string _Art_Gender;
		
		private System.Nullable<System.DateTime> _Art_Dob;
		
		private string _Art_Password;
		
		public log1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_ID", DbType="Int NOT NULL")]
		public int Art_ID
		{
			get
			{
				return this._Art_ID;
			}
			set
			{
				if ((this._Art_ID != value))
				{
					this._Art_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Name", DbType="VarChar(50)")]
		public string Art_Name
		{
			get
			{
				return this._Art_Name;
			}
			set
			{
				if ((this._Art_Name != value))
				{
					this._Art_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Email", DbType="VarChar(50)")]
		public string Art_Email
		{
			get
			{
				return this._Art_Email;
			}
			set
			{
				if ((this._Art_Email != value))
				{
					this._Art_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_phone", DbType="VarChar(11)")]
		public string Art_phone
		{
			get
			{
				return this._Art_phone;
			}
			set
			{
				if ((this._Art_phone != value))
				{
					this._Art_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Gender", DbType="VarChar(10)")]
		public string Art_Gender
		{
			get
			{
				return this._Art_Gender;
			}
			set
			{
				if ((this._Art_Gender != value))
				{
					this._Art_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Dob", DbType="Date")]
		public System.Nullable<System.DateTime> Art_Dob
		{
			get
			{
				return this._Art_Dob;
			}
			set
			{
				if ((this._Art_Dob != value))
				{
					this._Art_Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Password", DbType="VarChar(50)")]
		public string Art_Password
		{
			get
			{
				return this._Art_Password;
			}
			set
			{
				if ((this._Art_Password != value))
				{
					this._Art_Password = value;
				}
			}
		}
	}
	
	public partial class check1Result
	{
		
		private int _Art_ID;
		
		private string _Art_Name;
		
		private string _Art_Email;
		
		private string _Art_phone;
		
		private string _Art_Gender;
		
		private System.Nullable<System.DateTime> _Art_Dob;
		
		private string _Art_Password;
		
		public check1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_ID", DbType="Int NOT NULL")]
		public int Art_ID
		{
			get
			{
				return this._Art_ID;
			}
			set
			{
				if ((this._Art_ID != value))
				{
					this._Art_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Name", DbType="VarChar(50)")]
		public string Art_Name
		{
			get
			{
				return this._Art_Name;
			}
			set
			{
				if ((this._Art_Name != value))
				{
					this._Art_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Email", DbType="VarChar(50)")]
		public string Art_Email
		{
			get
			{
				return this._Art_Email;
			}
			set
			{
				if ((this._Art_Email != value))
				{
					this._Art_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_phone", DbType="VarChar(11)")]
		public string Art_phone
		{
			get
			{
				return this._Art_phone;
			}
			set
			{
				if ((this._Art_phone != value))
				{
					this._Art_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Gender", DbType="VarChar(10)")]
		public string Art_Gender
		{
			get
			{
				return this._Art_Gender;
			}
			set
			{
				if ((this._Art_Gender != value))
				{
					this._Art_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Dob", DbType="Date")]
		public System.Nullable<System.DateTime> Art_Dob
		{
			get
			{
				return this._Art_Dob;
			}
			set
			{
				if ((this._Art_Dob != value))
				{
					this._Art_Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Password", DbType="VarChar(50)")]
		public string Art_Password
		{
			get
			{
				return this._Art_Password;
			}
			set
			{
				if ((this._Art_Password != value))
				{
					this._Art_Password = value;
				}
			}
		}
	}
	
	public partial class forgetResult
	{
		
		private int _Art_ID;
		
		private string _Art_Name;
		
		private string _Art_Email;
		
		private string _Art_phone;
		
		private string _Art_Gender;
		
		private System.Nullable<System.DateTime> _Art_Dob;
		
		private string _Art_Password;
		
		public forgetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_ID", DbType="Int NOT NULL")]
		public int Art_ID
		{
			get
			{
				return this._Art_ID;
			}
			set
			{
				if ((this._Art_ID != value))
				{
					this._Art_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Name", DbType="VarChar(50)")]
		public string Art_Name
		{
			get
			{
				return this._Art_Name;
			}
			set
			{
				if ((this._Art_Name != value))
				{
					this._Art_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Email", DbType="VarChar(50)")]
		public string Art_Email
		{
			get
			{
				return this._Art_Email;
			}
			set
			{
				if ((this._Art_Email != value))
				{
					this._Art_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_phone", DbType="VarChar(11)")]
		public string Art_phone
		{
			get
			{
				return this._Art_phone;
			}
			set
			{
				if ((this._Art_phone != value))
				{
					this._Art_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Gender", DbType="VarChar(10)")]
		public string Art_Gender
		{
			get
			{
				return this._Art_Gender;
			}
			set
			{
				if ((this._Art_Gender != value))
				{
					this._Art_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Dob", DbType="Date")]
		public System.Nullable<System.DateTime> Art_Dob
		{
			get
			{
				return this._Art_Dob;
			}
			set
			{
				if ((this._Art_Dob != value))
				{
					this._Art_Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Password", DbType="VarChar(50)")]
		public string Art_Password
		{
			get
			{
				return this._Art_Password;
			}
			set
			{
				if ((this._Art_Password != value))
				{
					this._Art_Password = value;
				}
			}
		}
	}
	
	public partial class emailcheckResult
	{
		
		private int _Art_ID;
		
		private string _Art_Name;
		
		private string _Art_Email;
		
		private string _Art_phone;
		
		private string _Art_Gender;
		
		private System.Nullable<System.DateTime> _Art_Dob;
		
		private string _Art_Password;
		
		public emailcheckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_ID", DbType="Int NOT NULL")]
		public int Art_ID
		{
			get
			{
				return this._Art_ID;
			}
			set
			{
				if ((this._Art_ID != value))
				{
					this._Art_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Name", DbType="VarChar(50)")]
		public string Art_Name
		{
			get
			{
				return this._Art_Name;
			}
			set
			{
				if ((this._Art_Name != value))
				{
					this._Art_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Email", DbType="VarChar(50)")]
		public string Art_Email
		{
			get
			{
				return this._Art_Email;
			}
			set
			{
				if ((this._Art_Email != value))
				{
					this._Art_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_phone", DbType="VarChar(11)")]
		public string Art_phone
		{
			get
			{
				return this._Art_phone;
			}
			set
			{
				if ((this._Art_phone != value))
				{
					this._Art_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Gender", DbType="VarChar(10)")]
		public string Art_Gender
		{
			get
			{
				return this._Art_Gender;
			}
			set
			{
				if ((this._Art_Gender != value))
				{
					this._Art_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Dob", DbType="Date")]
		public System.Nullable<System.DateTime> Art_Dob
		{
			get
			{
				return this._Art_Dob;
			}
			set
			{
				if ((this._Art_Dob != value))
				{
					this._Art_Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Password", DbType="VarChar(50)")]
		public string Art_Password
		{
			get
			{
				return this._Art_Password;
			}
			set
			{
				if ((this._Art_Password != value))
				{
					this._Art_Password = value;
				}
			}
		}
	}
	
	public partial class mobcheckResult
	{
		
		private int _Art_ID;
		
		private string _Art_Name;
		
		private string _Art_Email;
		
		private string _Art_phone;
		
		private string _Art_Gender;
		
		private System.Nullable<System.DateTime> _Art_Dob;
		
		private string _Art_Password;
		
		public mobcheckResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_ID", DbType="Int NOT NULL")]
		public int Art_ID
		{
			get
			{
				return this._Art_ID;
			}
			set
			{
				if ((this._Art_ID != value))
				{
					this._Art_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Name", DbType="VarChar(50)")]
		public string Art_Name
		{
			get
			{
				return this._Art_Name;
			}
			set
			{
				if ((this._Art_Name != value))
				{
					this._Art_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Email", DbType="VarChar(50)")]
		public string Art_Email
		{
			get
			{
				return this._Art_Email;
			}
			set
			{
				if ((this._Art_Email != value))
				{
					this._Art_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_phone", DbType="VarChar(11)")]
		public string Art_phone
		{
			get
			{
				return this._Art_phone;
			}
			set
			{
				if ((this._Art_phone != value))
				{
					this._Art_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Gender", DbType="VarChar(10)")]
		public string Art_Gender
		{
			get
			{
				return this._Art_Gender;
			}
			set
			{
				if ((this._Art_Gender != value))
				{
					this._Art_Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Dob", DbType="Date")]
		public System.Nullable<System.DateTime> Art_Dob
		{
			get
			{
				return this._Art_Dob;
			}
			set
			{
				if ((this._Art_Dob != value))
				{
					this._Art_Dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Art_Password", DbType="VarChar(50)")]
		public string Art_Password
		{
			get
			{
				return this._Art_Password;
			}
			set
			{
				if ((this._Art_Password != value))
				{
					this._Art_Password = value;
				}
			}
		}
	}
	
	public partial class pickcatResult
	{
		
		private int _C_ID;
		
		private string _C_Name;
		
		private string _C_pic;
		
		private string _C_r;
		
		private string _C_s;
		
		public pickcatResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_ID", DbType="Int NOT NULL")]
		public int C_ID
		{
			get
			{
				return this._C_ID;
			}
			set
			{
				if ((this._C_ID != value))
				{
					this._C_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string C_Name
		{
			get
			{
				return this._C_Name;
			}
			set
			{
				if ((this._C_Name != value))
				{
					this._C_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_pic", DbType="VarChar(50)")]
		public string C_pic
		{
			get
			{
				return this._C_pic;
			}
			set
			{
				if ((this._C_pic != value))
				{
					this._C_pic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_r", DbType="VarChar(50)")]
		public string C_r
		{
			get
			{
				return this._C_r;
			}
			set
			{
				if ((this._C_r != value))
				{
					this._C_r = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_s", DbType="VarChar(10)")]
		public string C_s
		{
			get
			{
				return this._C_s;
			}
			set
			{
				if ((this._C_s != value))
				{
					this._C_s = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
